### ISSUE TITLE
More issues - sorry.

### ISSUE THREAD

**Issue by gauntface** [haydenbleasel/gulp-favicons#1]
I was trying to get this into the WSK build and we have two builds, a quick to serve version and a distribution version, at the moment I'm getting it half working with one or the other.

- [x] If you don't define a html attribute in the the config it will actually overwrite the input html file AND move a copy to the gulp.dest() location.
- [x] The naming of everything is super weird for this context, 'dest' in files could be any number of things and isn't clear.
- [x] The naming for android_chrome_manifest.json isn't totally right, the manifest we are using I believe is a web standard and other browsers should be supporting it at some point (i.e. FF)
- [x] We need a way to support multiple HTML files, something we can't do at the moment cleanly. How much of this is due to the use of the real-favicon API?
- [x] The windows icons for windows phone are plain white for our white logo on blue background
- [ ] On Chrome stable, because there is no <link rel="shortcut icons"....> there is no icon supplied. The manifest is only picked up in Chrome Beta.
- [ ] Also had some issues with iOS 8 (the app icon and start up screen weren't getting used)

**Comment by haydenbleasel** [comment]
@gauntface No worries, now that the module is a lot simpler I can easily get around to fixing these issues. Just need a couple of days :)

**Comment by haydenbleasel** [comment]
@gauntface Okay so after going through all the issues and feature requests that are coming up, we've decided that our architecture needs fixing. Long story short, I'm getting rid of Favicons and just joining RFG to make node modules. We've also come up with a solution for offline support which will be easier to implement with the new structure. To make things simple:

**Currently:**
![artboard-1](https://cloud.githubusercontent.com/assets/4142719/5997451/81119ee2-ab0f-11e4-8f0c-3d1de8efe056.png)

**What we need:**
![artboard-3](https://cloud.githubusercontent.com/assets/4142719/5997452/81127574-ab0f-11e4-9ed6-9d6915c5c1df.png)

So yeah, working on this now and keeping all these issues in mind.

**Comment by gauntface** [comment]
That's great news, thanks @haydenbleasel for the info.

**Comment by haydenbleasel** [comment]
Hey @gauntface, we've got Favicons in a really good position now. All the issues are fixed (except for the above two which are unknown and being addressed right now), it's faster, neater, scalable, etc and no more external dependencies. Feel free to test it against WSK and let me know how it goes.

**Comment by haydenbleasel** [comment]
Moving these last pieces into https://github.com/haydenbleasel/favicons/issues/70
