### ISSUE TITLE
Is there any tutorial how to use this Gulp plugin? 

### ISSUE THREAD

**Issue by jitendravyas** [haydenbleasel/gulp-favicons#13]

**Comment by mkstix6** [comment]
I'm also having trouble following the few instructions that are provided.
A little more expansion on the setup would be greatly appreciated.

**Comment by kennygfunk** [comment]
Agreed

**Comment by haydenbleasel** [comment]
Hey guys, as per the new README, you can check out http://favicons.io for a sample Gulp configuration or https://github.com/haydenbleasel/favicons/ for the full list. As noted, the Gulp plugin has one extra property for writing to HTML files.
