### ISSUE TITLE
Getting error with v1 and v2 doest seem to work properly

### ISSUE THREAD

**Issue by jerepaajanen** [haydenbleasel/gulp-favicons#14]
I'm using v 1.0.9, that worked nicely since latest favicon update. Seems like v1.0.9 has latest favicons as dependency, it needs node 4 and my project uses 0.12.

I also tried new favicons in different project, seems to work nicely with node4, but I cannot use <link rel="favicons" href="..." /> tag anymore, does it really require <head> tags to work? I like to build favicons to partial file with just favicon data, and preprocess it to other html files.

**Comment by haydenbleasel** [comment]
Hey @jerepaajanen, we've dropped all support for old favicons builds because they're totally busted, so let's try to get this issue solved ASAP. Currently the HTML property allows you to define a string or array of strings of HTML files, and it'll write metadata to each one. Do you need a different output?

**Comment by jerepaajanen** [comment]
How does that string work, if I like to output favicons to lets say partials/favicons.html and place where I have put ```<!-- favicons -->```
I tried 2.0.4 and still cant get this to work with my build, getting error: 
```
.../node_modules/gulp-favicons/node_modules/favicons/index.js:1
(function (exports, require, module, __filename, __dirname) { (() => {
                                                                ^
SyntaxError: Unexpected token )
```

**Comment by haydenbleasel** [comment]
@jerepaajanen There's no more HTML attributes or comments. The HTML property works like:

`html: 'index.html'` or `html: ['index.html','layout.html']`

What are your Node and Gulp-Favicons versions? (`node -v` for Node)

**Comment by jerepaajanen** [comment]
Updated to node 4.x, doesn't seem to run on 0.12.x... Now getting error on favicons.html, which is empty by default.

**Comment by haydenbleasel** [comment]
Yeah it uses ES6 which is 4.0+. What's your favicons.html error?

**Comment by jerepaajanen** [comment]
```
Starting 'images:favicons'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '.../node_modules/gulp-favicons/src/partials/favicons.html'
```

Seems to look file from wrong place.

**Comment by haydenbleasel** [comment]
Okay, can I see your Gulpfile?

**Comment by jerepaajanen** [comment]
Sure

```
return gulp.src(paths.images.src + '/favicon.png')
        .pipe($.if(isProduction, $.favicons({
            appName: config.title,
            appDescription: config.description,
            developerName: pkg.author,
            developerURL: pkg.homepage,
            background: 'transparent',
            url: config.siteURL,
            path: 'images/favicons',
            display: 'standalone',
            orientation: 'portrait',
            version: 1.0,
            logging: false,
            online: false,
            html: paths.src + 'partials/favicons.html'
        })))

        .pipe(gulp.dest(paths.dest));
```

**Comment by haydenbleasel** [comment]
Okay, this is strange. 2 things we could try:

1. Completely remove gulp-favicons and do a fresh install (the parent module Favicons has been getting updates all day today)
2. Send me your complete Gulpfile and I'll test it out myself (could be an edge case I haven't run into)

**Comment by jerepaajanen** [comment]
Made fresh install and changed html to 
```
html: '../../' + paths.src + 'partials/favicons.html'
```

plugin tries to lookup html files inside node_modules.

**Comment by haydenbleasel** [comment]
Okay, this must be an edge case issue for your project, and I think it's based on your project's architecture. Just so it's clear, the path to the HTML file should be relative to your current working directory. If that's not the case, then I'd need to see your project to resolve this.

**Comment by jerepaajanen** [comment]
Here's my current project: https://github.com/jerepaajanen/RAE-Framework/tree/gulp-workflow

**Comment by haydenbleasel** [comment]
Hey @jerepaajanen, your project helped me uncover a bug in `gulp-favicons` path relativity. Can you install `2.0.6` and run again? Sorry for the trouble so far.

**Comment by jerepaajanen** [comment]
Seems to work perfectly, thanks for a great plugin!

**Comment by haydenbleasel** [comment]
No problem :)
