### ISSUE TITLE
Missing files when generating favicons

### ISSUE THREAD

**Issue by vn38minhtran** [haydenbleasel/gulp-favicons#19]
- Missing `android-chrome-manifest.json`
- Missing `apple-touch-startup-image-1024x748.png`
- Missing `apple-touch-startup-image-2048x1496.png`

**Comment by haydenbleasel** [comment]
Hey @vn38minhtran, duplicate content was fixed in `gulp-favicons@2.1.2` so I'll rename this issue.

**Comment by vn38minhtran** [comment]
Ok. Thanks!

**Comment by haydenbleasel** [comment]
Moving this issue to https://github.com/haydenbleasel/favicons/issues/69 since it's the source of the issue :)
