### ISSUE TITLE
call syntax seems inverted

### ISSUE THREAD

**Issue by jessaustin** [haydenbleasel/gulp-favicons#2]
I've tried to integrate `gulp-favicons` into my `gulpfile`, and I've just about given up in favor of just using `favicons` directly. I think the reason is that `gulp-favicons` is mostly about creating favicons, yet it's called as if it were mostly about writing `<link rel= >` tags. What would make sense to me would be something like:
```javascript
data = require('gulp-data') # etc.
gulp.task('favicons', function() {
    return gulp.src(['src/small-favicon.png', 'src/large-favicon.png'])
        .pipe(favicons({settings: { background: '#1d1d1d' }})
        .pipe(gulp.dest('./'));
});
gulp.task('html', ['favicons'], function() {
    return gulp.src('src/**/*.jade')
        .pipe(data(function() {
            return {linkRels: favicons.linkRels()};
        }))
        .pipe(jade())
        .pipe(gulp.dest('./'));
});
```
The point is that it's good to keep the favicons in the stream, rather than writing them to disk like `grunt` would. One might want to do something to the original image before passing it to `gulp-favicons`, or one might want to transform the generated favicons somehow.

Another point (and frankly what started me on this) is that `gulp-favicons` should not be in the templating business. It's great that it produces a sequence of `<link rel= >` tags, but it should be willing to just pass that string along rather than insisting on writing it to disk or inserting it into an already-existing stream. Let `gulp-jade` et al. worry about that.

I'll write a patch if this doesn't sound like a terrible idea?

**Comment by haydenbleasel** [comment]
Sounds like an excellent idea mate :) I totally agree with everything, just haven't had time to do anything about it as I've been focusing on improving Favicons and the RFG API that it uses. If you could do this I'm sure many people will be grateful! Good luck champ.

**Comment by sgade** [comment]
+1
Would love to see this.

**Comment by thasmo** [comment]
Absolutely +1!
