### ISSUE TITLE
Gulp wrapper example

### ISSUE THREAD

**Issue by johnholtripley** [haydenbleasel/gulp-favicons#22]
Hi
I'm trying to get either favicons or gulp-favicons working within my Gulp task, but I'm always getting a
```SyntaxError: Unexpected token }```
error.
I'm on Windows if that's an issue, and my lastest attempt was this:
```
gulp.task('favicons', function() {
    gulp.src('htdocs/images/favicon-source.png').pipe(favicons({
        appName: "Autumn Earth",
        appDescription: "Community site",
        developerName: null,
        developerURL: null,
        background: "#212121",
        path: "htdocs/images/icons/",
        url: "http://www.autumnearth.com/",
        display: "browser",
        orientation: "portrait",
        version: "1.0",
        logging: true,
        online: false,
        icons: {
            android: true,
            appleIcon: true,
            appleStartup: true,
            coast: true,
            favicons: true,
            firefox: true,
            opengraph: true,
            twitter: true,
            windows: true,
            yandex: true
        },
    html: "test/index.html"         // HTML files to modify. `string` or `array` 
    })).pipe(gulp.dest('./htdocs/images/icons/'))
});
```

Am I doing anything wrong here? Thanks for any help, and thanks for making such a useful task

**Comment by haydenbleasel** [comment]
Hey @johnholtripley, I copied this configuration into a fresh gulpfile with just:

```
var gulp = require('gulp'),
    favicons = require('gulp-favicons');
```

It worked perfectly, so not sure what the issue is. Potential errors I can think of include a fault somewhere else in the gulpfile, an outdated module or a syntax error in your HTML. Can you verify any of these? Also, what version of Node are you running? (`node -v`)

**Comment by sagikazarmark** [comment]
Works fine with latest node (4.2.3), but not with older versions (like widely spread 0.12). I guess it is related to some ES5 incompatibility as I get this error message:

```
node_modules/favicons/index.js:7
(() => {
  ^
SyntaxError: Unexpected token )
```

**Comment by haydenbleasel** [comment]
Hey @johnholtripley and @sagikazarmark, I've updated the module to specifically use the ES5 version of Favicons. Can you please update to `gulp-favicons@2.1.4` and check whether this error still occurs?

**Comment by johnholtripley** [comment]
thanks - yes my Node version was 0.12
