### ISSUE TITLE
"opengraph: false" erroring

### ISSUE THREAD

**Issue by johnholtripley** [haydenbleasel/gulp-favicons#23]
Hi,
Everything is now working beautifully, the only slight issue is when I disable the Open Graph image (which I need to handle independently to get the article image rather than a favicon image), but setting `opengraph: false` in the icons parameters causes the following error: 
```C:\Autumn Earth\Dropbox\autumn-earth\site\node_modules\favicons\helpers.js:253
                        Reflect.deleteProperty(request.favicon_design, 'open_g
                        ^
ReferenceError: Reflect is not defined
    at Object.configure (C:\Autumn Earth\Dropbox\autumn-earth\site\node_modules\favicons\helpers.js:253:25)```
any idea?
I can set the Twitter card image to false without any problem - it just seems to be the Open Graph that causes the issue.

thanks

**Comment by haydenbleasel** [comment]
Hey @johnholtripley, it looks like the actual root of this problem is Node not understanding Reflect, which is an ES6 object. As the new version (`gulp-favicons@2.1.4`) uses ES5 by default, I would recommend updating your module and double-checking that it works :)

**Comment by johnholtripley** [comment]
Hi - I've just updated Node to v5.2.0 and using gulp-favicons 2.1.4 and still getting the issue - any ideas?
thanks

**Comment by IanCaunce** [comment]
I have run into the same issue. It only occurs when `online` is set to true. Any set of icons can be set to false, not just `opengraph` for the issue to occur. Running v5.1.1 of node.

**Comment by haydenbleasel** [comment]
Streamable API has merged into Favicons so we're tracking the issue from there now.
