### ISSUE TITLE
Lock in favicons at backwards compatible version

### ISSUE THREAD

**Issue by mattdrose** [haydenbleasel/gulp-favicons#27]
Hey there.

An update to `favicons` started breaking my builds recently:

```
build	11-Dec-2015 11:10:18	     [exec] gulp:
build	11-Dec-2015 11:10:24	     [exec]      [exec] 
build	11-Dec-2015 11:10:24	     [exec]      [exec] /var/data/atlassian/application-data/bamboo/xml-data/build-dir/CP-WEB58-JOB1/web/node_modules/gulp-favicons/node_modules/favicons/index.js:7
build	11-Dec-2015 11:10:24	     [exec]      [exec] (() => {
build	11-Dec-2015 11:10:24	     [exec]      [exec]   ^
build	11-Dec-2015 11:10:24	     [exec]      [exec] SyntaxError: Unexpected token )
```

I'm sure I can fix it on my end by updating Node.js or something, but doesn't it make sense to [lock in a `favicons` version](https://github.com/haydenbleasel/gulp-favicons/blob/master/package.json#L29) so builds don't suddenly break?

Thanks for your work on this repo.

**Comment by haydenbleasel** [comment]
Hey @mattdrose, absolutely. I set Favicons to * back when it was a smaller module so it should be resolved for future use. I'll get this done very soon.

**Comment by haydenbleasel** [comment]
Fixed in `gulp-favicons@2.2.1`

**Comment by mattdrose** [comment]
Thank you. Out of curiosity, how do you publish your versions? I noticed the version on gh@master is different than the one published on npm. Do you just publish local w/o pushing to gh?

**Comment by haydenbleasel** [comment]
@mattdrose Yeah it's because it's not published from this repo as of 10 minutes ago. See #28 for details.

**Comment by mattdrose** [comment]
Ah nice. I like it when modules are build agnostic. Especially when there's a new popular build tool every 6 months 😕

**Comment by haydenbleasel** [comment]
Yeah exactly haha. The main module exposes a typical node-style function and a stream function. Since Gulp is simply a stream wrapper, it makes sense to be part of the main module.
