### ISSUE TITLE
basic example for gulp?

### ISSUE THREAD

**Issue by v3nt** [haydenbleasel/gulp-favicons#7]
I can't seem to get favicon to work at all but it probably is my code! I can't find any examples that seem to work. My errors are below...

my files & destinations are all there.

    files: {
              src: 'assets/img/images/reform-re-favicon.png',
              dest: 'dist/images',
              html: 'views/favicons.twig'
            },
            settings: { background: '#1d1d1d' }
into  

    gulp.task('favicons', function() {
    return gulp.src(['src/small-favicon.png', 'src/large-favicon.png'])
        .pipe(favicons({settings: { background: '#1d1d1d' }})
        .pipe(gulp.dest('./dist/images'));
    });

errors from running 'gulp favicons'

/Users/jynk/Projects/634 Reform Architects/website/reform-website-master/wp-content/themes/reform/gulpfile.js:171
        .pipe(gulp.dest('dist/images');
                                      ^
SyntaxError: Unexpected token ;
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)

**Comment by bscheibe** [comment]
Did you end up getting this working? 

Currently all it's throwing an error on the semi-colon at the end of that `.pipe(gulp.dest('dist/images');` line. Try removing that and see what happens.

Another option would be to download the repo itself and cd into the test folder and run gulp. You can see how it works in action and also have the code to work off of.

**Comment by haydenbleasel** [comment]
There are a lot of changes happening with `favicons` and `gulp-favicons` at the moment so it might be due to this. I'll look into it really soon though :)

**Comment by bscheibe** [comment]
Thanks! After double checking - I'm pretty sure the forwarding to the html file from the `html: ...` isn't currently working. Just a heads up.

**Comment by v3nt** [comment]
not yet and used it with grunt instead for now. I'll check back when i work on that again.

**Comment by haydenbleasel** [comment]
Hey guys, the version of `favicons` and `gulp-favicons` should fix up all these issues. Open up a new issue if you find something is broken :)
