### ISSUE TITLE
Absolute url

### ISSUE THREAD

**Issue by jerepaajanen** [haydenbleasel/gulp-favicons#8]
Hi,
Is there a way to se absolute url for open graph image, because facebook doesn't recognize relative paths. I have set <link rel="canonical" href="..." /> to my index.html file, but that doesn't seem to do anything.

**Comment by haydenbleasel** [comment]
Hey @jerepaajanen, can i have a code example please?

**Comment by jerepaajanen** [comment]
Sure, here's gulpfile:
`gulp.task('dist:favicons', function () {
        return gulp.src(paths.dest + 'index.html')
            .pipe($.favicons({
                files: {
                    dest: '.' + paths.dest,
                    iconsPath: '/'
                },
                settings: {
                    background: '#ffffff'
                }
            }))
            .pipe(gulp.dest(paths.dest))
            .pipe($.size({
                gzip: false,
                showFiles: false,
                title: 'Favicons'
            }));
    });`

I have also in my index.html:
<title>...</title>
<meta name="author" content="..." />
<meta name="description" content="..." />
<link rel="canonical" href="..." />
<link rel="favicons" href="..." />

**Comment by haydenbleasel** [comment]
Hey @jerepaajanen, sorry for the delay. We're covering this in the parent module: https://github.com/haydenbleasel/favicons/issues/57
