### ISSUE TITLE
Trouble with icon destination path

### ISSUE THREAD

**Issue by gmhenderson** [haydenbleasel/gulp-favicons#9]
Hello, I'm having some trouble getting my destination paths working. Consider:

```
gulp.task('favicons', function () {
    return gulp.src('src/templates/_layout.html')
        .pipe(favicons({
            files: {
                src: 'src/img/favicon.png',
                dest: 'dist/img/icons',
                pathIcons: 'img/icons'
            }
        }))
        .pipe(gulp.dest('dist/templates'));
});
```

Given that, here's what I'm expecting vs. what I'm actually getting:

|                        | Expected                      | Actual                        |
|------------------------|-------------------------------|-------------------------------|
| HTML file location:     | `dist/templates/_layout.html` | `dist/templates/_layout.html` |
| `<link>` href like:          | `img/icons/favicon.ico`       | `dist/img/icons/favicon.ico`  |
| Icon files located in: | `dist/img/icons`              | `src/templates/dist/img/icons`  |

I've tried using the `base` option with `gulp.src` but I can't seem to get it working. How can I get the paths setup as I expect? Thanks.

**Comment by mattdrose** [comment]
+1

I'm finding the same problem here.

Usually paths are relative to `gulpfile.js`.

**Comment by mattdrose** [comment]
I think my gripe is the following line in `index.js`:

```
options.files.dest = path.join(path.dirname(file.path), options.files.dest);
```

It's dangerous to assume that your web resources are located relative to your templates, considering most apps use complicated file structures.

I'm using this on a Symfony 2 project. Views are located in `app/Resources/views/`, while web resources are located in `web/src/`. This is what my config looks like:

```
favicons: {
    src: views + '/default/favicons.twig',
    dest: views + '/default',
    files: {
      src: src + '/images/logos/favicon.png',
      dest: '../../../../web/' + dest + '/images/logos',
      iconsPath: dest + '/images/logos'
    }
}
```

**Comment by haydenbleasel** [comment]
Perhaps strip out my logic and require absolute paths for everything? Would give more flexibility, I just assumed it was helping people initially.

**Comment by mattdrose** [comment]
Yea, I think it would be helpful for basic html sites. I'm just an edge case.

Maybe there could be a `basePath` option or something.

**Comment by haydenbleasel** [comment]
Still, tools shouldn't make assumptions about your app structure. I think I'll just remove this logic :)

**Comment by mattdrose** [comment]
Cool. Thanks for your help.
